# STAGE 1: Build layer (De 'keuken')
FROM node:lts-alpine AS build-stage
WORKDIR /app

# Kopieer alles naar de container
COPY . .

# De 'ontvanger' voor de versie uit de pipeline (--build-arg)
ARG APP_VERSION=unknown

# De 'magic' stap: vervang {{VERSION}} dynamisch door de waarde van APP_VERSION
RUN find . -type f -name "*.html" -o -name "*.js" | xargs sed -i "s/{{VERSION}}/${APP_VERSION}/g"

# STAGE 2: Production layer (Het 'bord')
FROM nginx:stable-alpine AS production-stage
# Kopieer de bewerkte bestanden van de build-stage naar de Nginx map
COPY --from=build-stage /app /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]