apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: NodePort # Verander dit van LoadBalancer naar NodePort
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234 # We leggen hem vast op 31234, dat test makkelijker
